version: '3.9'

services:
  miner:
    image: ghcr.io/bit-current/hivetrain:latest
    restart: 'always'
    ipc: host
    depends_on:
      - vpn
    network_mode: service:vpn
    tty: true
    stdin_open: true
    build:
      shm_size: '4gb'
      dockerfile: Dockerfile
    volumes:
      - ./hivetrain:/hivetrain/hivetrain
      - ./data:/data
      - ./wallets:/root/.bittensor/wallets
    # privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
    environment:
      NETUID: ${NET_UID:-25}
      WALLET_NAME: ${WALLET_NAME:-default}
      WALLET_HOTKEY: ${WALLET_HOTKEY:-defaulthotkey}
      DHTPORT: ${DHT_PORT:-42316}
      AXONPORT: ${AXON_PORT:-42310}
    env_file:
      - .env

  validator:
    image: ghcr.io/bit-current/hivetrain:latest
    entrypoint: bash ./entrypoint-validator.sh
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ./hivetrain:/hivetrain/hivetrain
      - ./wallets:/root/.bittensor/wallets
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
    environment:
      NETUID: ${NET_UID:-25}
      WALLET_NAME: ${WALLET_NAME:-default}
      WALLET_HOTKEY: ${WALLET_HOTKEY:-defaulthotkey}
      DHTPORT: ${DHT_PORT:-42316}
      AXONPORT: ${AXON_PORT:-42310}
    env_file:
      - .env

  vpn:
    image: tailscale/tailscale:latest
    hostname: tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY:-tskey-client-kAbSnX3CNTRL-bs9oeHznKB8HJMQTWvAcB8XquoYBW2jt}
      TS_EXTRA_ARGS: --advertise-tags=tag:member
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
    env_file:
      - .env
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
